In [22]:
from google.colab import drive
# drive mount
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [23]:
import pandas as pd
from sklearn.svm import SVC
import numpy as np
import matplotlib.pyplot as plt
import os #or shuttle and advance that os
from skimage.io import imread # imread to read image
from sklearn.model_selection import train_test_split
from skimage.transform import resize #to edit size

In [24]:
cat = os.listdir("/content/drive/MyDrive/Colab Notebooks/Cat")

In [25]:
dog = os.listdir("/content/drive/MyDrive/Colab Notebooks/Dog")

In [26]:
len(os.listdir("/content/drive/MyDrive/Colab Notebooks/Cat"))
len(os.listdir("/content/drive/MyDrive/Colab Notebooks/Dog"))

68

In [27]:
# join
catpath=os.path.join("/content/drive/MyDrive/Colab Notebooks","Cat")
for img in os.listdir(catpath):
  print(img)


cat.97.jpg
cat.73.jpg
cat.79.jpg
cat.78.jpg
cat.80.jpg
cat.89.jpg
cat.90.jpg
cat.92.jpg
cat.70.jpg
cat.67.jpg
cat.77.jpg
cat.74.jpg
cat.84.jpg
cat.82.jpg
cat.81.jpg
cat.86.jpg
cat.93.jpg
cat.96.jpg
cat.91.jpg
cat.65.jpg
cat.83.jpg
cat.69.jpg
cat.87.jpg
cat.99.jpg
cat.38.jpg
cat.36.jpg
cat.60.jpg
cat.53.jpg
cat.75.jpg
cat.59.jpg
cat.76.jpg
cat.43.jpg
cat.41.jpg
cat.98.jpg
cat.44.jpg
cat.58.jpg
cat.66.jpg
cat.49.jpg
cat.50.jpg
cat.46.jpg
cat.64.jpg
cat.88.jpg
cat.71.jpg
cat.72.jpg
cat.68.jpg
cat.94.jpg
cat.40.jpg
cat.85.jpg
cat.95.jpg
cat.52.jpg
cat.54.jpg
cat.113.jpg
cat.112.jpg
cat.115.jpg
cat.56.jpg
cat.114.jpg
cat.109.jpg
cat.107.jpg
cat.102.jpg
cat.108.jpg
cat.57.jpg
cat.106.jpg
cat.37.jpg
cat.55.jpg
cat.100.jpg
cat.48.jpg
cat.119.jpg
cat.42.jpg
cat.103.jpg
cat.63.jpg
cat.45.jpg
cat.117.jpg
cat.39.jpg
cat.61.jpg
cat.105.jpg
cat.62.jpg
cat.110.jpg
cat.35.jpg
cat.47.jpg
cat.116.jpg
cat.101.jpg
cat.111.jpg
cat.104.jpg
cat.51.jpg
cat.118.jpg


In [28]:
dogpath = os.path.join("/content/drive/MyDrive/Colab Notebooks","Dog")
for img in os.listdir(dogpath):
  print(img)

dog.63.jpg
dog.7.jpg
dog.8.jpg
dog.9.jpg
dog.65.jpg
dog.6.jpg
dog.58.jpg
dog.66.jpg
dog.62.jpg
dog.64.jpg
dog.39.jpg
dog.68.jpg
dog.57.jpg
dog.49.jpg
dog.60.jpg
dog.61.jpg
dog.43.jpg
dog.47.jpg
dog.67.jpg
dog.4.jpg
dog.50.jpg
dog.56.jpg
dog.51.jpg
dog.5.jpg
dog.48.jpg
dog.44.jpg
dog.38.jpg
dog.59.jpg
dog.53.jpg
dog.55.jpg
dog.35.jpg
dog.42.jpg
dog.34.jpg
dog.36.jpg
dog.32.jpg
dog.25.jpg
dog.41.jpg
dog.45.jpg
dog.27.jpg
dog.46.jpg
dog.31.jpg
dog.30.jpg
dog.54.jpg
dog.3.jpg
dog.40.jpg
dog.37.jpg
dog.26.jpg
dog.28.jpg
dog.52.jpg
dog.29.jpg
dog.20.jpg
dog.22.jpg
dog.33.jpg
dog.12.jpg
dog.21.jpg
dog.14.jpg
dog.24.jpg
dog.19.jpg
dog.18.jpg
dog.16.jpg
dog.13.jpg
dog.17.jpg
dog.11.jpg
dog.1.jpg
dog.15.jpg
dog.2.jpg
dog.10.jpg
dog.23.jpg


In [29]:
flat_data_arr = [] # to collect input
target_arr = [] # to collect output
categories = ["Cat","Dog"]
datadir="/content/drive/MyDrive/Colab Notebooks"

In [30]:
for i in categories:
  print("Load categories.....")
  path=os.path.join(datadir,i)
  for img in os.listdir(path):
    img_arr=imread(os.path.join(path,img))
    img_resize = resize(img_arr,(150,150,3))
    flat_data_arr.append(img_resize.flatten()) # Corrected 'flattern' to 'flatten'
    target_arr.append(categories.index(i))
  print("Loaded completly",i)

Load categories.....
Loaded completly Cat
Load categories.....
Loaded completly Dog


In [31]:
flat_data_arr

[array([0.47976095, 0.36642162, 0.32647723, ..., 0.40213642, 0.42617976,
        0.48892486]),
 array([1., 1., 1., ..., 1., 1., 1.]),
 array([0.99215686, 0.99215686, 0.99215686, ..., 0.55959467, 0.33754688,
        0.02164526]),
 array([0.63296216, 0.49178569, 0.4290406 , ..., 0.610482  , 0.12481651,
        0.24752336]),
 array([0.30229051, 0.29444737, 0.21209443, ..., 0.58856487, 0.57287859,
        0.52581977]),
 array([0.62174572, 0.46390087, 0.45058549, ..., 0.15976958, 0.12452896,
        0.1188809 ]),
 array([0.26771534, 0.21675126, 0.14219251, ..., 0.20014238, 0.19229925,
        0.14524042]),
 array([0.40138102, 0.38569475, 0.35040063, ..., 0.21570573, 0.10909371,
        0.03597407]),
 array([0.13627252, 0.19509448, 0.1833303 , ..., 0.8493572 , 0.47586824,
        0.53573409]),
 array([0.74680098, 0.66483396, 0.5706102 , ..., 0.57267973, 0.51340612,
        0.48596613]),
 array([0.09019608, 0.02745098, 0.03137255, ..., 0.71204153, 0.72616381,
        0.74382259]),
 array([0.4

In [32]:
flat_data = np.array(flat_data_arr) #covert to array
tarata = np.array(target_arr)
df=pd.DataFrame(flat_data) #convert to dataframe
df["target"]=target_arr
df

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,target
0,0.479761,0.366422,0.326477,0.497796,0.378511,0.336458,0.519553,0.389613,0.342338,0.524326,...,0.431083,0.458534,0.521279,0.413828,0.441070,0.503815,0.402136,0.426180,0.488925,0
1,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.999999,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0
2,0.992157,0.992157,0.992157,0.992129,0.992129,0.992129,0.989770,0.989770,0.989770,0.988239,...,0.525972,0.317098,0.013726,0.560639,0.350321,0.042462,0.559595,0.337547,0.021645,0
3,0.632962,0.491786,0.429041,0.631940,0.490763,0.428018,0.624366,0.483190,0.420445,0.620148,...,0.574872,0.140164,0.253456,0.603285,0.142313,0.259381,0.610482,0.124817,0.247523,0
4,0.302291,0.294447,0.212094,0.305703,0.297860,0.215507,0.308719,0.300876,0.218523,0.308718,...,0.594982,0.579296,0.532237,0.591976,0.576290,0.529231,0.588565,0.572879,0.525820,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0.768130,0.691507,0.619205,0.562160,0.443307,0.340889,0.623372,0.472422,0.342538,0.606955,...,0.953688,0.958069,0.897416,0.957814,0.962249,0.901571,0.950053,0.954488,0.893809,1
149,0.246750,0.255539,0.368698,0.262558,0.267077,0.373934,0.276302,0.273717,0.374262,0.281503,...,0.455897,0.385309,0.432369,0.469203,0.398615,0.447326,0.480224,0.409636,0.464329,1
150,0.720659,0.608868,0.484345,0.788838,0.698053,0.589112,0.699704,0.640619,0.565847,0.694656,...,0.802625,0.783017,0.759488,0.796551,0.776943,0.753413,0.797203,0.777595,0.754066,1
151,0.562609,0.466070,0.253184,0.531096,0.417403,0.202458,0.519534,0.393667,0.170831,0.488835,...,0.389573,0.366044,0.318985,0.392066,0.368537,0.321478,0.393571,0.370042,0.322983,1


In [33]:
y=df.iloc[:,-1].values
x=df.iloc[:,:-1].values
x

array([[0.47976095, 0.36642162, 0.32647723, ..., 0.40213642, 0.42617976,
        0.48892486],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.99215686, 0.99215686, 0.99215686, ..., 0.55959467, 0.33754688,
        0.02164526],
       ...,
       [0.72065869, 0.60886784, 0.48434497, ..., 0.79720318, 0.77759534,
        0.75406593],
       [0.56260885, 0.46606989, 0.25318399, ..., 0.39357094, 0.37004153,
        0.3229827 ],
       [0.84878496, 0.82525555, 0.77819672, ..., 0.84478071, 0.81986949,
        0.70555633]])

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train = train_test_split(x,y,test_size=0.2,random_state=0)

In [35]:
from sklearn.svm import SVC
model = SVC()
model.fit(x_train,y_train)

SVC()

In [36]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0])

In [37]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_pred,y_test)

0.5483870967741935

In [38]:
path1 = "/content/drive/MyDrive/Colab Notebooks/cat.37.jpg"
img = imread(path1)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])

In [39]:
path2 = "/content/drive/MyDrive/Colab Notebooks/dog.7.jpg"
img=imread(path2)
img=resize(img,(150,150,3)).flatten().reshape(1,-1)
model.predict(img)

array([0])